### ISSUE TITLE
Small issue with train_LP.py file

### ISSUE THREAD

**Issue by hzlihang99** [RinneSz/CLGA#7]
Hi,

I think at the line 41: `model(x_1, edge_adj_1, sparse=False)` is incorrect, as the model's forward function only take the edge_index as input and there is no the third parameter for that function. I replace it with `model(x_1, edge_index_1)` and the issue is fixed.

**Comment by Jakehuang2** [comment]
Hello, I encountered the same issue as you, and after following your method to fix it, I ran into a new problem. The error message still points to the same line of code. Have you encountered this issue?


Traceback (most recent call last):
  File "D:\graphProject\CLGA-main\train_LP.py", line 156, in <module>
    loss = train()
  File "D:\graphProject\CLGA-main\train_LP.py", line 46, in train
    z1 = model(x_1, edge_adj_1)
  File "D:\Anaconda\envs\CLGA\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\graphProject\CLGA-main\pGRACE\model.py", line 61, in forward
    return self.encoder(x, edge_index)
  File "D:\Anaconda\envs\CLGA\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\graphProject\CLGA-main\pGRACE\model.py", line 38, in forward
    x = self.activation(self.conv[i](x, edge_index))
  File "D:\Anaconda\envs\CLGA\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\hjh_ppp\AppData\Local\Temp\hjh_ppp_pyg_jit\tmpie9538sn.py", line 192, in forward
    self.improved, self.add_self_loops, dtype=x.dtype)
  File "D:\Anaconda\envs\CLGA\lib\site-packages\torch_geometric\nn\conv\gcn_conv.py", line 57, in gcn_norm
    edge_index, edge_weight, fill_value, num_nodes)
  File "D:\Anaconda\envs\CLGA\lib\site-packages\torch_geometric\utils\loop.py", line 125, in add_remaining_self_loops
    edge_index = torch.cat([edge_index[:, mask], loop_index], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 0. Got 2 and 2708 (The offending index is 0)
